server:
  port: 8090
spring:
  application:
    name: knowledge-base-geteway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.66.11.210:8848
        namespace: public
        register-enabled: true # 是否注册为服务
        username: nacos
        password: nacos
        cluster-name: DEFAULT
        metadata: {
          "nacos.discovery.metadata.region": "cn-hangzhou",
        }
    gateway:
      server:
        webflux:
          #global-filter:
          #  adapt-cached-body:
          #    enabled: true
          #  reactive-load-balancer-client:
          #    enabled: true
          httpclient:
            connect-timeout: 10000
            response-timeout: 30s
            pool:
              max-idle-time: 10s
          routes:
            - id: knowledge-base-service
              uri: lb://knowledge-base-server
              predicates:
                - Path=/api/**
              metadata:
                response-timeout: -1 # 禁用响应超时，避免 SSE 中断
              filters:
                - name: StripPrefix
                  args: {
                    parts: 1
                  }
                - name: AddResponseHeader
                  args: {
                    name: "X-Request-Start",
                    value: "hello"
                  }
                - name: CircuitBreaker
                  args: {
                    name: "knowledge-base-service",
                    fallbackUri: "forward:/fallback",
                    statusCodes: "404,500,503"
                  }
    openfeign:
      okhttp:
        enabled: true
    loadbalancer:
      nacos:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


resilience4j:
  circuitbreaker:
    instances:
      knowledge-base-service:
        wait-duration-in-open-state:
          seconds: 20
        failureRateThreshold: 50
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        permitted-number-of-calls-in-half-open-state: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter: trace